version: 0.2

env:
  parameter-store:
    VUE_APP_COGNITO_LOGIN_URL: "/HadxSampleProject/Cognito/login_page"
    S3_BUCKET_NAME: "/HadxSampleProject/S3/bucket/contents"
    CLOUDFRONT_DISTRIBUTION_ID: "/HadxSampleProject/CloudFront/distribution_id"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
      
  build:
    commands:
      - echo "Building Vue.js application..."
      - npm run build
      
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync dist s3://$S3_BUCKET_NAME/dist/ --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - echo "Deployment completed successfully!"

# artifacts:
#   files:
#     - '**/*'
#   base-directory: dist
#   
# cache:
#   paths:
#     - node_modules/**/* 